theme: jekyll-theme-modernist
title: Directory Services Internals
author:
  name: Michael Grafnetter
  twitter: MGrafnetter

logo: /favicon.png

twitter:
  username: MGrafnetter
  card: summary

social:
  name: Michael Grafnetter
  links:
    - https://twitter.com/MGrafnetter
    - https://www.linkedin.com/in/grafnetter
    - https://github.com/MichaelGrafnetter

feed:
  en: /feed_en.xml
  sk: /feed_sk.xml

plugins:
 - jekyll-redirect-from
 - jekyll-seo-tag

exclude:
  - '.git/'
  - '.vs/'
  - '*.TMP'
  - '*.sh'