theme: jekyll-theme-modernist
title: Directory Services Internals
author:
  name: &author_name Michael Grafnetter
  twitter: &twitter_handle "MGrafnetter"
  github: MichaelGrafnetter

logo: /favicon.png

twitter:
  username: *twitter_handle
  card: summary

social:
  name: *author_name
  links:
    - https://twitter.com/MGrafnetter
    - https://www.linkedin.com/in/grafnetter
    - https://github.com/MichaelGrafnetter

plugins:
 - jekyll-redirect-from
 - jekyll-seo-tag

exclude:
  - 'Gemfile'
  - '.git/'
  - '.vs/'
  - '*.TMP'
  - '*.sh'