title: DSInternals
tagline: Directory Services Internals
description: Directory Services Internals
logo: /favicon.png
logo_large: /assets/images/logo_white.png
url: https://www.dsinternals.com

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/dsinternals_transparent_black_large.png

show_excerpts: true
excerpt_separator: <!--more-->

author:
  name: "Michael Grafnetter"
  twitter: MGrafnetter
  github: MichaelGrafnetter
  linkedin: grafnetter

twitter:
  username: MGrafnetter
  card: summary

remote_theme: jekyll/minima
minima:
  skin: solarized-dark
  social_links:
    - { platform: github, user_url: "https://github.com/MichaelGrafnetter", title: "GitHub: MichaelGrafnetter" }
    - { platform: x, user_url: "https://twitter.com/MGrafnetter", title: "Twitter: @MGrafnetter" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/grafnetter/", title: "LinkedIn: grafnetter" }

kramdown:
  toc_levels: 2..2

plugins:
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-remote-theme
 - jekyll-github-metadata

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'CNAME'
  - '.git/'
  - '.vs/'
  - '*.TMP'
  - '*.sh'
  - '*.ps1'
  - 'vendor'
