title: DSInternals
tagline: Directory Services Internals
description: Directory Services Internals
logo: /favicon.png
logo_large: /assets/images/logo_white.png

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/dsinternals_transparent_black_large.png

show_excerpts: true
excerpt_separator: <!--more-->

author:
  name: &author_name "Michael Grafnetter"
  twitter: &twitter_handle "MGrafnetter"
  github: &github_handle MichaelGrafnetter
  linkedin: &linkedin_handle grafnetter
  keybase: &keybase_handle grafnetter

twitter:
  username: *twitter_handle
  card: summary

google_site_verification: DrNJpqz9Fl4sLlwL6coniSeHoQjmo9OuetqP7lry6zI

remote_theme: jekyll/minima
minima:
  skin: solarized-dark
  social_links:
    twitter: *twitter_handle
    linkedin: *linkedin_handle
    keybase: *keybase_handle
    github: *github_handle

plugins:
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-remote-theme

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'CNAME'
  - '.git/'
  - '.vs/'
  - '*.TMP'
  - '*.sh'
  - '*.ps1'
