title: DSInternals
tagline: Directory Services Internals
description: Directory Services Internals
logo: /favicon.png
logo_large: /assets/images/logo_white.png
url: https://www.dsinternals.com

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/dsinternals_transparent_black_large.png

show_excerpts: true
excerpt_separator: <!--more-->

author:
  name: "Michael Grafnetter"
  twitter: MGrafnetter
  github: MichaelGrafnetter
  linkedin: grafnetter

twitter:
  username: MGrafnetter
  card: summary

theme: minima
minima:
  skin: solarized-dark
  social_links:
    -  title: "GitHub: MichaelGrafnetter"
       icon: github
       url: "https://github.com/MichaelGrafnetter"
    - title: "X: @MGrafnetter"
      icon: x-twitter
      url: "https://x.com/MGrafnetter"
    - title: "LinkedIn: grafnetter"
      icon: linkedin
      url: "https://www.linkedin.com/in/grafnetter/"

kramdown:
  toc_levels: 2..2

sass:
  style: compressed

safe: true
whitelist:
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-github-metadata
 - jekyll-relative-links
 - jemoji
plugins:
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-github-metadata
 - jekyll-relative-links
 - jemoji

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'CNAME'
  - '.git/'
  - '.vs/'
  - '*.TMP'
  - '*.sh'
  - '*.ps1'
  - 'vendor'
