# theme: jekyll-theme-modernist
title: Directory Services Internals
logo: /favicon.png
excerpt_separator: <!--more-->

author:
  name: &author_name "Michael Grafnetter"
  twitter: &twitter_handle "MGrafnetter"
  github: MichaelGrafnetter
  linkedin: grafnetter

twitter:
  username: *twitter_handle
  card: summary

social:
  name: *author_name
  links:
    - https://twitter.com/MGrafnetter
    - https://www.linkedin.com/in/grafnetter
    - https://github.com/MichaelGrafnetter

google_site_verification: DrNJpqz9Fl4sLlwL6coniSeHoQjmo9OuetqP7lry6zI

plugins:
 - jekyll-redirect-from
 - jekyll-seo-tag

exclude:
  - 'Gemfile'
  - '.git/'
  - '.vs/'
  - '*.TMP'
  - '*.sh'
